### ISSUE TITLE
Do not force the engine version

### ISSUE THREAD

**Issue by elboletaire** [luzzif/bittrex-api-client#3]
Please, do not force the engine version.

You can ask for a greater version instead, changing it from `8.4.0` to `^8.4.0` or `>=8.4.0` should be enough.

**Comment by luzzif** [comment]
Thanks for pointing out. Fixed in 1.7.14.

**Comment by elboletaire** [comment]
Thank you for fixing it! Now I can comfortably use the current lts version 😃
